/*
* @ reducers actions constants
*/

/**
 *  navigation constants
 */ 
export const PAGE_HOME = 'PAGE_HOME';
export const PAGE_EDIT_WORKOUT = 'PAGE_EDIT_WORKOUT';
export const PAGE_TIMER_WORKOUT = 'PAGE_TIMER_WORKOUT';
export const PAGE_CREATE_WORKOUT = 'PAGE_CREATE_WORKOUT';

/**
 *  navigation activity
 */ 
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS';
export const CREATE_WORKOUT_FAILED = 'CREATE_WORKOUT_FAILED';

export const EDIT_WORKOUT_SUCCESS = 'EDIT_WORKOUT_SUCCESS';
export const EDIT_WORKOUT_FAILED = 'EDIT_WORKOUT_FAILED';

export const DELETE_WORKOUT_SUCCESS = 'DELETE_WORKOUT_SUCCESS';
export const DELETE_WORKOUT_FAILED = 'DELETE_WORKOUT_FAILED';

export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS';
export const FETCH_WORKOUTS_FAILED = 'FETCH_WORKOUTS_FAILED';

export const LOAD_RUNNING_WORKOUT_SUCCESS = 'LOAD_RUNNING_WORKOUT_SUCCESS';
export const LOAD_RUNNING_WORKOUT_FAILED = 'LOAD_RUNNING_WORKOUT_FAILED';
